### ISSUE TITLE
Blokcslider on Adapt Authoring?

### ISSUE THREAD

**Issue by kzfabi** [LearningPool/adapt-contrib-blockslider#4]
Is it possible to get this extension working on the Adapt Authoring?

**Comment by drehrindia** [comment]
Hi,
Can we use this extension on the Adapt Authoring? I cannot find it in the extension list.

**Comment by jscampos** [comment]
It does not come with Adapt Builder. I tried adding it but I get the error "Error: Unrecognized plugin type for package adapt-contrib-blockslider", is there any work-around this issue? I'm using Adapt Builder v0.1.2 and Adapt Framework v2.0.2.
